### ISSUE TITLE
Add Google Analytics tracking

### ISSUE THREAD

**Issue by eps90** [eps90/pull-request-notifier#3]
Events:

### General
- [x] Background process start
- [x] Connecting to server

###  Popup: 
- [x] Popup open
- [x] Opening PR from popup
- [x] Tabs switching
- [x] Preview opening
- [x] Sending a reminder from list
- [x] Sending a reminder from preview
- [x] Opening PR from preview

### Notifications:
- [x] Opening PR from notification

### Options page
- [x] Opening

Custom timings:

- [x] How long is popup opened
- [x] How long notification is shown
